spring:

  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/devlife
    username: soobi
    password:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4= # 임의의 문자열을 Base64로 인코딩한 값
  refresh-expiration-time: 604800000  # 1000 * 60 * 60 * 24 * 7 => 7일
  access-expiration-time:  1800000 # 1000 * 60 * 30 => 30분