spring:
  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path
    # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db;MODE=MYSQL
      username: hh
      password: 1234

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/devlife
#    username: postgres
#    password: 1234
  thymeleaf:
    prefix: classpath:/static/

  jpa:
    generate-ddl: 'true' # 추가한 테스트용 라인
    open-in-view: false # 추가한 테스트용 라인

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create # 추가한 테스트용 라인

#    hibernate:
#      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4= # 임의의 문자열을 Base64로 인코딩한 값
  refresh-expiration-time: 604800000  # 1000 * 60 * 60 * 24 * 7 => 7일
  access-expiration-time:  1800000 # 1000 * 60 * 30 => 30분